### ISSUE TITLE
Freshman can double sign packets 

### ISSUE THREAD

**Issue by greendayandcats** [ComputerScienceHouse/packet#100]
Mostly just a UI issue, but if on floor freshmen with new accounts log into packet.csh, they are given the ability to 'resign' current active packets

**Comment by JoelEager** [comment]
It's actually a flaw in our backend account checking. It's fixed in https://github.com/ComputerScienceHouse/packet/pull/99 which should be out soon.

Thanks for the heads up.

**Comment by greendayandcats** [comment]
Update: it puts the double freshman signature into the off-floor/alumni category
