### ISSUE TITLE
I cannot sign packets with a disabled accounts

### ISSUE THREAD

**Issue by squablyScientist** [ComputerScienceHouse/packet#101]
I cannot sign packets witha  disabled account

**Comment by JoelEager** [comment]
I can't help you but this might: https://members.csh.rit.edu/~dgonyeo/hrp.pdf

**Comment by squablyScientist** [comment]
I cannot access that link without an account either

**Comment by JoelEager** [comment]
Well I'll just have to print a copy out for you then.
