### ISSUE TITLE
Generate .csv for easier data munging

### ISSUE THREAD

**Issue by zthart** [ComputerScienceHouse/packet#113]
From talking with @devinmatte, it sounds like the only metrics output available currently is a .txt file that lists data for intro members in a human readable format. 

Sometimes, though, I don't want to read the data myself because I'm lazy and computers can do the hard work for me. If, in addition to the .txt file, there was a way to generate a .csv/.json/something else format file that was quick and easy to read programmatically, it would be easier to manipulate that data and create some useful metrics or maybe even a fun 𝓼𝓹𝓻𝓮𝓪𝓭𝓼𝓱𝓮𝓮𝓽 of packet data.

**Comment by devinmatte** [comment]
In the meantime, I'm likely going to build a csv option into the results command so that evals can at least generate and keep a csv
