### ISSUE TITLE
Add double quote linting

### ISSUE THREAD

**Issue by devinmatte** [ComputerScienceHouse/packet#165]
Have pylint check for double/single quote usage throughout the app

**Comment by mxmeinhold** [comment]
@devinmatte I found [this pylint plugin](https://github.com/edaniszewski/pylint-quotes) that should allow for this.

What kind of config would you be looking at? I think this relatively follows styling within PEP examples.

```ini
string-quote=single
triple-quote=single
docstring-quote=double
```

**Comment by devinmatte** [comment]
@mxmeinhold Go for it. In doing so I'd prefer single quotes to be the norm
