### ISSUE TITLE
Endpoint to get packet score

### ISSUE THREAD

**Issue by devinmatte** [ComputerScienceHouse/packet#176]
Conditional should be able to pull packet scores automatically from packet. I want to create 2 endpoints for getting this information:

- [x] `/v1/packets/{username}` - Which collects all packets that person has completed and their start and end dates and id
- [x] `/v1/packet/{packetId}` - Displays the scores of the packet in question

Potential Route:
- [x] `/v1/packet/{username}/newest` - Which collects the newest packet that person has completed and their start and end dates and scores (For easy use with services like conditional)

Implementation conditional side should be described in an issue on that repo

**Comment by mxmeinhold** [comment]
@devinmatte Should packet scores be just raw scores or would you also like percentages?
