### ISSUE TITLE
packet.py using ldap breaks SOC rules

### ISSUE THREAD

**Issue by zedoax** [ComputerScienceHouse/packet#44]
Using LDAP in packet.py to check an intromember breaks Joel's sole source of truth for the database

**Comment by devinmatte** [comment]
Without expanding the schema to include this information, which currently only applies to a few members, it will remain. It also seems like overkill to roll that information into the DB

**Comment by zedoax** [comment]
I was actually going to make a PR fixing this later. There doesn't need to be a modification to the DB. packet.py simply needs to use the DB as it's sole Source of truth, but ldap can still be queried in shared.py, which is where ldap info should be queried

**Comment by JoelEager** [comment]
`packet.py` was deleted in v3.1.0, https://github.com/ComputerScienceHouse/packet/pull/99 so this shouldn't be an issue now.
