### ISSUE TITLE
Incorrect Button Color

### ISSUE THREAD

**Issue by sgreene570** [ComputerScienceHouse/packet#53]
![2018-09-04-194606_483x269_scrot](https://user-images.githubusercontent.com/17414243/45063313-5ba7f500-b07b-11e8-87f3-aee4d4d59129.png)

Why is the button pale??????

**Comment by sgreene570** [comment]
somebody plz fix I am laze

**Comment by sgreene570** [comment]
@WillNilges

**Comment by WillNilges** [comment]
Okay, Gimme sec

**Comment by WillNilges** [comment]
Waait. I think this might require an account to test and fix because it requires the bootstrap and sweetalert. So I might need access to potate or something.
