### ISSUE TITLE
Off-Floor Upperclassmen/Alumni/Advisor Signatures Not Highlighted Green

### ISSUE THREAD

**Issue by JimDaGuy** [ComputerScienceHouse/packet#60]
![packet_issue](https://user-images.githubusercontent.com/22183239/45113578-c4917a80-b118-11e8-886d-d771be985655.PNG)

**Comment by devinmatte** [comment]
I have to check how this looks. I'm fairly certain this is ui parody of talpacket, but I'll see how it looks
