### ISSUE TITLE
Allow updating packets to current layout of floor

### ISSUE THREAD

**Issue by devinmatte** [ComputerScienceHouse/packet#8]
The current plan is to initialize all packets with the current layout of floor, but in the case that floors layout changes, we need to be able to update all currently live packets with new data from LDAP.
There should be a button available to the evals director for that purpose

**Comment by mbillow** [comment]
We have had a lot of discussion around this and in general the consensus was that a member's packet shouldn't change after it starts. Especially in the case that someone new moves on floor and we would be increasing their requirements.

**Comment by devinmatte** [comment]
@mbillow The adding of new requirements makes sense, but the removal of requirements is also important if someone moves off. I'm more of the opinion that packet should not be locked, and should reflect the layout of floor at the end of it
