### ISSUE TITLE
Odd Fraction Issues (84 instead of 83)

### ISSUE THREAD

**Issue by bmbowdish** [ComputerScienceHouse/packet#91]
https://www.csh.rit.edu/~bmbowdish/packet_issues/83.png
https://www.csh.rit.edu/~bmbowdish/packet_issues/84.png

Here is the example of the issue I noticed. 

It seems like you compensate for Sostre not being able to sign his packet on the Active Packets page, but not the personal page.

**Comment by zedoax** [comment]
This is a known issue.  The fix is currently in #90 The way we pulled the sigs worked in testing, but not in prod.
